
services:
  personaapi-dotnet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=arq_per_db;User Id=SA;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

networks:
    my_network:
        driver: bridge

volumes:
  mssql_data: